name: Generate 3D Contribution Calendar

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution Graph
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: yoshi389111/github-profile-3d-contrib@0.7.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: mankarmanas

      - name: Commit & Push
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add -A .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "auto: update 3D contribution calendar"
            git pull --rebase origin main
            git push
          fi
